In [1]:
import pandas as pd
pd.set_option("display.max_rows", 5)
reviews = pd.read_csv("./Data/winemag-data-130k-v2.csv", index_col=0)


print("Setup complete.")

reviews.head()

Setup complete.

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [2]:
reviews_per_country = reviews.country.value_counts()

In [3]:
reviews_per_country

country
US        54504
France    22093
          ...
China         1
Egypt         1
Name: count, Length: 43, dtype: int64

In [4]:
centered_price = reviews.price - reviews.price.mean()

In [5]:
reviews['points_price'] = reviews.points/reviews.price
reviews.points_price.dropna
max(reviews.points_price).title

AttributeError: 'float' object has no attribute 'title'

In [ ]:
bargain_wine = reviews.loc[(reviews.points/reviews.price).idxmax()].title
bargain_wine

'Bandit NV Merlot (California)'

In [ ]:
reviews['counts_tropical'] = reviews['description'].str.count('tropical')
reviews

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,points_price,counts_tropical
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,NaN,1
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,5.800000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,90,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss,2.812500,0
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,90,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit,4.285714,0

In [16]:

descriptor_counts = reviews.description.apply(
    lambda p:'tripical' if p.count('tropical') > p.count('fruity') else 'fruity'
).value_counts()

descriptor_counts

description
fruity      126569
tripical      3402
Name: count, dtype: int64

In [18]:
reviews.shape

(129971, 14)

In [ ]:
descriptor_counts = pd.Series({'tropical':reviews.description.str.count("tropical").sum(),'fruity':reviews.description.str.count("fruity").sum()})
descriptor_counts

tropical    3703
fruity      9259
dtype: int64

In [19]:
descriptor_counts = pd.Series({'tropical':reviews.description.str.count("tropical"),'fruity':reviews.description.str.count("fruity")})
descriptor_counts

tropical    0         1
1         0
         ..
129969    ...
fruity      0         0
1         1
         ..
129969    ...
dtype: object

In [31]:
descriptor_counts = reviews.description.map(lambda p: p.count('tropical')).sum()
descriptor_counts

np.int64(3703)

In [32]:
descriptor_counts = reviews.description.map(lambda p: p.count('fruity')).sum()
descriptor_counts

np.int64(9259)

In [ ]:
descriptor_counts = pd.Series({'tropical': reviews.description.str.count('tropical').sum(), 'fruity': reviews.description.str.count('fruity').sum()}, index=['tropical', 'fruity']) 
descriptor_counts

tropical    3703
fruity      9259
dtype: int64

In [48]:
descriptor_counts = pd.Series({'tropical': reviews.description.str.count('tropical').sum(), 'fruity': reviews.description.str.count('fruity').sum()}, index=['tropical', 'fruity']) 
descriptor_counts

tropical    3703
fruity      9259
dtype: int64

In [54]:

descriptor_counts = pd.Series([reviews.description.str.count("tropical").sum(),reviews.description.str.count("fruity").sum()], index=['tropical', 'fruity']) 
descriptor_counts

tropical    3703
fruity      9259
dtype: int64

In [51]:
n_trop = reviews.description.map(lambda desc: "tropical" in desc).sum()
n_fruity = reviews.description.map(lambda desc: "fruity" in desc).sum()

descriptor_counts = pd.Series([n_trop, n_fruity], index=['tropical', 'fruity'])
descriptor_counts

tropical    3607
fruity      9090
dtype: int64

In [68]:
def count_tropical(row):
    k =0
    if 'tropical' in row.description:
        k = k+1 
    return k

def count_fruity(row):
    k =0
    if 'fruity' in row.description:
        k = k+1 
    return k
descriptor_counts = pd.Series([reviews.apply(count_tropical,axis='columns').value_counts()[1], reviews.apply(count_fruity,axis='columns').value_counts()[1]],index=['tropical', 'fruity'])
descriptor_counts

tropical    3607
fruity      9090
dtype: int64

In [71]:
def star_rating(row):
    if row.country == 'Canada':
        return 3
    elif 95 <= row.points:
        return 3
    elif 85 <= row.points < 95:
        return 3
    else:
        return 1

star_ratings = pd.Series(reviews.apply(star_rating, axis='columns'))
star_ratings

0         3
1         3
         ..
129969    3
129970    3
Length: 129971, dtype: int64